### ISSUE TITLE
[FIX] : Make page responsive

### ISSUE THREAD

**Issue by ayusshh19** [CSI-DMCE-2023/Shopping-Website-PHP-HacktoberFest-2023#5]
Description : - 
Page isnt responsive with respect to mobile view and also testmonial cards creating overflow content issue.

Video : -

https://github.com/ayusshh19/Hacktoberfest-php/assets/89308426/e3f49d30-d294-459d-a8f3-7bcc041750ff

Expected Outcome : -

- [ ]  No horizontal scroll enable for mobile view 
- [ ]  Make testimonial cards responsive
- [ ]  Navbar content visible

**Comment by mohit-negi** [comment]
@ayusshh19  Please assign me this issue

**Comment by ayusshh19** [comment]
Sure you can work !

**Comment by mohit-negi** [comment]
Hey @ayusshh19, I am stuck at the 'connect.db at line 6' 
Here are the logs, which may help you track down the issue
Website
> C:\xampp\htdocs\Shopping-Website-PHP-HacktoberFest-2023\dbconnect.php on line 6

VSCode
> C:\xampp\htdocs\Shopping-Website-PHP-HacktoberFest-2023\dbconnect.php:6
Stack trace:
#0 {main}
  thrown in C:\xampp\htdocs\Shopping-Website-PHP-HacktoberFest-2023\dbconnect.php on line 6

I'm familiar with Java Springboot, SQL, and some front-end technologies, but I'm struggling to set up a local instance of the website due to my inexperience with PHP and tools like phpMyAdmin. I've carefully followed the contributors' instructions, but I'm still running into problems. Could you help me get past this hurdle so I can focus on the task at hand?

**Comment by ayusshh19** [comment]
Make Database namec- "shopping" in your phpmyadmin import sql file in the code

**Comment by ayusshh19** [comment]
Hey @mohit-negi create a new database name "hacktoberfest" and import a sql file which i have provided in this repository 

https://github.com/CSI-DMCE-2023/Shopping-Website-PHP-HacktoberFest-2023/assets/89308426/e2743f47-91f2-4705-953e-41ee3adc7433

**Comment by mohit-negi** [comment]
well your way of instructing someone is not right, you have mentioned 
>  import a sql file which i have provided
I was unable to contribute because I did not receive the necessary files or instructions to access the repository. Additionally, I encountered issues connecting to the database due to an existing connection to SQL Workbench. I apologize for any inconvenience this may cause.
Thanks

**Comment by OMPOL1705** [comment]
Please assign this issue to me.
